version: "3.8"

services:
  minihub:
    image: ghcr.io/cs0663c/minihub:latest
    # build: .
    container_name: minihub
    ports:
      - "8080:8000"
    volumes:
      - minihub_data:/data
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
      - DISABLE_REGISTRATION=${DISABLE_REGISTRATION:-false}
    restart: unless-stopped

volumes:
  minihub_data:
